### ISSUE TITLE
G82 & G83 Drilling Operations

### ISSUE THREAD

**Issue by IdefixRC** [teodoryantcheff/SolidCam-Mach3-Post#4] opened 2017-01-26 11:42 UTC
Hi guys,

first of all: AMAZING WORK and thanks a lot for doing this.
I have tested the post processor on a 3 Axis Machine and had some issues with the Spot and Deep drill operations.

Spot Drilling will output the following code:
( -------------------- )
( 4-SPOT DRILL - DRILL )
( -------------------- )
G0 X23. Y9.615 Z10. A0.
G82 Z-2.79 R0.21 P0 F200
  X40.2 Y9.615 Z0.21
  X57.4 Y9.615 Z0.21
  X74.6 Y9.615 Z0.21
  X91.8 Y9.615 Z0.21
  X109. Y9.615 Z0.21
G80
( ---- End of 4-Spot Drill ---- )

Mach 3 (at least mine) does the first hole as planned but then moves to hole 2 at height 0.21 only, does not spot drill and move on to the next holes.

Same effect with deep drilling:
( ------------------------- )
( 5-4.2MM-DEEPDRILL - DRILL )
( ------------------------- )
G0 X23. Y9.615 Z10. A0.
G83 Z-7.732 R0.21 Q0. P0 F200
  X40.2 Y9.615 Z0.21
  X57.4 Y9.615 Z0.21
  X74.6 Y9.615 Z0.21
  X91.8 Y9.615 Z0.21
  X109. Y9.615 Z0.21
G80
( ---- End of 5-4.2mm-DeepDrill ---- )

I manually edited the code to add the G83/G82 string after each re-positioning move and it works fine after that.

Did I do something wrong?

Thanks !

**Comment by teodoryantcheff** [comment] 2017-01-31 12:03
Hey. Thanks for the feedback. I'll to reproducing this soon and will come back to you.
BTW do try running your code through PostDevTestMachine as post processor. I can't recall just now how I have set up drilling cycles. PostDev is the latest post...

**Comment by teodoryantcheff** [comment] 2017-02-02 21:20
So - I'm almost sure you are not running PostDevTestMachine. Do try that and let me know. Also which version of Mach.
PostDev is the post that I was using for the new implementation and need to properly rename it and delete it after so people do not get confused.

Cheers,

**Comment by biqut2** [comment] 2017-11-16 21:23
I experience the same issue. I have to uncheck the use drill cycle option to drill more than one hole per operation.

**Comment by IdefixRC** [comment] 2017-11-17 00:20
Using PostDev works perfectly for me. Thanks

**Comment by teodoryantcheff** [comment] 2017-11-17 15:38
@biqut2 did you try the postdev post ? 
I definitely need to make that the "default" so that people do not get confused with the older version.

**Comment by biqut2** [comment] 2017-11-18 13:09
I just looked an no I was not. I was using the Mach3_4X version. The PostDevTestMachine.gpp post-processor does not have this issue. The following lines fix this:

{' F'feed}
    ;{nb, ' ', ' X'xpos, ' Y'ypos, ' Z'zpos}

I did notice something that is consistent across both files and it is the following line: {nb, 'G0 G40 G49 G80 G21'} I always have to go in and edit this to changed the G21 to G20. Wouldn't it be better if this were not hardcoded like this?

**Comment by teodoryantcheff** [comment] 2017-11-18 16:20
Yeah, we need to make this dependent on the units used in the source part but since I'm a metric guy I
 have hardcoded that to G21. Will check what I can do about that.

**Comment by teodoryantcheff** [comment] 2017-11-18 17:12
@biqut2 bbe26ee6e24970cac9163c5f84275e207c8c5ab9 should be solving that. Try it please and let me know.

**Comment by teodoryantcheff** [comment] 2017-11-18 18:47
Closing that issue. If G21/20 is still a problem please open a new ticket.

**Closed as completed by teodoryantcheff** 2017-11-18 18:47 UTC
